// <auto-generated />
namespace KatmanliMimari_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EkleDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EkleDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202202170722451_EkleDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
